### ISSUE TITLE
Cannot run this repo with most recent version of jest.

### ISSUE THREAD

**Issue by danielbh** [wallabyjs/wallaby-jest-sample#2] opened 2016-10-18 16:24 UTC
Any idea whats going on? Thanks.

jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?
Error: Cannot find module 'jest-config/build/normalize'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by ArtemGovorov** [comment] 2016-10-18 22:42
What version of `npm` you're using (`npm -v`) and what version of `jest-cli` is installed? Just tried with the latest `16.0.1` (that gets installed with the sample) and it's working for me. Could you please check if the `node_modules/jest-config/build/normalize.js` file exists locally after the `npm install`?

**Comment by danielbh** [comment] 2016-10-19 07:51
Currently using npm version 2.15.9
The file normalize.js is present but not in top level node_modules directory. It is installed as a sub-dependency of jest-cli.  
This is for Webstorm by the way.

**Comment by ArtemGovorov** [comment] 2016-10-19 08:05
> Currently using npm version 2.15.9

This was the issue, wallaby jest integration was expecting npm 3 module structure. The issue is fixed in core 1.0.307, [try forcing the core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to see if the issue has gone.

**Closed as completed by ArtemGovorov** 2016-10-19 08:05 UTC

**Comment by danielbh** [comment] 2016-10-19 09:56
Force update worked. Then it was just a matter of changing the wallaby.js file to work with a react project. Thanks.
